import Heading from "@/components/Heading";
import { Posts, Products } from "@/types/interfaces";
import { Metadata } from "next";

import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "All Products",
  description: "Generated by create next app",
};

interface postsProps extends Posts {}

async function getDate() {
  const res = await fetch("https://dummyjson.com/products");
  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

export default async function Products() {
  const data = await getDate();
  const products = data.products;
  return (
    <div className="mt-24">
      <Heading title="All Products" isCentered={true} />

      <div className="  capitalize  max-w-[62rem] mx-auto grid grid-cols-1 indent-2 md:grid-cols-3 lg:grid-cols-4 gap-4 py-6 px-4 ">
        <Image
          src="/bg2.png"
          width={1920}
          height={1080}
          alt="second banner"
          className=" fixed bg-repeat-y -z-50 w-[1400px] h-[670px] top-0 left-0 opacity-5"
        />

        {products.map((item: Products) => (
          <Link
            href={`/products/${item.id}`}
            className=" relative  bg-slate-800 hover:bg-slate-950 transition-all   p-4 shadow-2xl  border-cyan-700  py-2 my-2 text-center rounded-xl"
            key={item.id}
          >
              <small className=" rounded-tl-xl z-30 absolute bg-slate-800/70 px-1 top-0 left-0 text-sky-50 font-semibold">
                {item.brand}
                </small>
            <div className="flex max-h-[10rem] items-start ">
              <div className="relative">
                <Image
                  src={item.thumbnail}
                  width={370}
                  height={150}
                  alt="feature"
                  className="basis-5/12  max-h-40 rounded-xl shadow-lg"
                />

              
                <small className=" absolute bg-slate-800/50  bottom-0 right-0 text-sky-50 font-semibold">
                  -{item.discountPercentage}%
                </small>
              </div>
              
            </div>
            <div className="flex border-b-2 flex-col justify-center ">
                <h6 className="text-slate-100   ">
                {item.title}
                </h6>
                
              </div>
            <p className="  text-justify  indent-0 ">
              {item.description}
            </p>
          </Link>
        ))}
      </div>
    </div>
  );
}
