import Heading from "@/components/Heading";
import { Posts, Products } from "@/types/interfaces";
import { DollarSign, ShoppingCart, Star } from "lucide-react";

import Image from "next/image";
import Link from "next/link";
import { cache } from "react";

interface postsProps extends Posts {}

const getDate = cache(async (id: string) => {
  const res = await fetch(`https://dummyjson.com/products/${id}`);

  return res.json();
});

interface idParams {
  params: { id: string };
}

export async function generateMetadata({ params }: idParams) {
  const product = await getDate(params.id);
  return {
    title: product.title,
    description: "Generated by create next app",
  };
}

export default async function Product({ params: { id } }: idParams) {
  console.log(id);
  const item: Products = await getDate(id);

  return (
    <div className="container mt-24 ">
      <Heading title={`Product ${item.id}`} isCentered={true} />

      <div className=" relative flex flex-col mt-4 border-2 border-cyan-800 rounded-xl p-4 ">
        <article
          className={`relative flex flex-col lg:flex-row items-start bg-slate-800 justify-between gap-8  `}
        >
          <div className=" absolute right-0 top-0 h-16 w-16 text-sm flex items-center justify-center  rounded-full bg-cyan-800 text-white">
            -{item.discountPercentage} %
          </div>
          <Image
            src={item.thumbnail}
            width={370}
            height={370}
            alt="feature"
            className="basis-5/12 w-full rounded-xl shadow-lg"
          />
          <div className="basis-6/12 flex flex-col  md:text-center lg:text-start gap-4 md:gap-6">
            <Heading title={item.title} />

            <p className="lg:max-w-[40rem] text-justify mx-4">{item.description}</p>
            <div className=" relative">
              <div className="flex flex-wrap cursor-pointer capitalize">
                <p className=" flex  hover:text-yellow-400  w-fit bg-slate-700 rounded-lg shadow-2xl  m-2 p-2">
                  {" "}
                  price : {item.price} <DollarSign/>
                </p>
                <p className="  hover:text-yellow-400   w-fit bg-slate-700 rounded-lg shadow-2xl  m-2 p-2">
                  {" "}
                  rating : {item.rating}
                </p>
                <div className="flex items-center relative hover:text-yellow-400  w-fit bg-slate-700 rounded-lg shadow-2xl  m-2 p-2">
                  In Stock{" "}
                  <p className=" absolute -top-2 right-0">{item.stock} </p>{" "}
                  <ShoppingCart />
                </div>
                <div className="flex  px-4 my-2 w-fit bg-slate-700 rounded-lg shadow-2xl  m-2 p-2 hover:text-yellow-400  ">
                  <Star fill="#717F93" />
                  <Star fill="#717F93" />
                  <Star fill="#717F93" />
                  <Star />
                  <Star />
                </div>
              </div>
            </div>
          </div>
        </article>
        <section
          id="client"
          className=" items-center justify-center  max-w-[62rem] mx-auto grid grid-cols-1 md:grid-cols-3  lg:grid-cols-4  gap-4"
        >
          {item.images.map((image, index) => (
            <div key={index} className="relative">
              <Image
                src={image}
                width={150}
                height={100}
                alt={""}
                className="  w-full h-40 md:w-full mx-auto  rounded-lg   "
              />
              <div className=" absolute   bg-slate-400/50 hover:bg-slate-400/0   transition-all hover:cursor-pointer   w-full rounded-lg h-40 top-0 left-0"></div>
            </div>
          ))}
        </section>
      </div>
      <div className="  capitalize  max-w-[62rem] mx-auto grid grid-cols-1 indent-2 md:grid-cols-2 lg:grid-cols-3 gap-4 py-6 px-4 ">
        <Image
          src="/bg2.png"
          width={1920}
          height={1080}
          alt="second banner"
          className=" fixed bg-repeat-y -z-50 w-[1400px] h-[670px] top-0 left-0 opacity-5"
        />
      </div>
    </div>
  );
}
